"""create initial tables

Revision ID: 11b305d453a9
Revises:
Create Date: 2026-05-14 11:48:12.933308

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "11b305d453a9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actividad",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "descripcion", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False
        ),
        sa.Column("estado", sa.Boolean(), nullable=False),
        sa.Column("fecha", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "acudiente",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "nombre", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "parentesco", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column(
            "telefono", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column(
            "correo", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "complementario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "tipo_complementario",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
        sa.Column("anio", sa.Integer(), nullable=False),
        sa.Column("valor", sa.Integer(), nullable=False),
        sa.Column(
            "estado_complemento",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
        sa.Column("uso_matricula", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "docente",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "nombre", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "documento", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("estado", sa.Boolean(), nullable=False),
        sa.Column(
            "asignatura", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "grado",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "nombre", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "importacionautomatica",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "tipo_entidad", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column(
            "documento_identidad",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
        sa.Column("datos", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "estado", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("fecha_ingreso", sa.DateTime(), nullable=False),
        sa.Column("observacion", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "periodo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("periodo_electivo", sa.DateTime(), nullable=False),
        sa.Column("estado", sa.Boolean(), nullable=False),
        sa.Column("fecha", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tipoinventario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "nombre", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tipoinventario_nombre"), "tipoinventario", ["nombre"], unique=True
    )
    op.create_table(
        "usuario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("rol", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "contrasenia", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("estado", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "auditoria",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.Column(
            "tabla_nombre", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("registro_id", sa.Integer(), nullable=False),
        sa.Column(
            "operacion", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.Column("valor_anterior", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("valor_nuevo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fecha_accion", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_usuario"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "detalleactividades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("actividad_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actividad_id"],
            ["actividad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "estudiante",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("grado_id", sa.Integer(), nullable=False),
        sa.Column("acudiente_id", sa.Integer(), nullable=False),
        sa.Column(
            "nombre", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "documento", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("fecha_activo", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["acudiente_id"],
            ["acudiente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["grado_id"],
            ["grado.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inventario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("tipo_inventario_id", sa.Integer(), nullable=False),
        sa.Column(
            "nombre", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column(
            "estado_objeto", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "observacion", sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["tipo_inventario_id"],
            ["tipoinventario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parametrizarmatricula",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("grado_id", sa.Integer(), nullable=False),
        sa.Column("anio", sa.Integer(), nullable=False),
        sa.Column("valor", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grado_id"],
            ["grado.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parametrizarpension",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("grado_id", sa.Integer(), nullable=False),
        sa.Column("anio", sa.Integer(), nullable=False),
        sa.Column("valor", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grado_id"],
            ["grado.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rectoriaestado",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("docente_id", sa.Integer(), nullable=False),
        sa.Column("periodo_id", sa.Integer(), nullable=False),
        sa.Column("motivo_estado", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fecha_actualizacion", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["docente_id"],
            ["docente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["periodo_id"],
            ["periodo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rectoriaobservaciones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("docente_id", sa.Integer(), nullable=False),
        sa.Column("periodo_id", sa.Integer(), nullable=False),
        sa.Column(
            "descripcion", sqlmodel.sql.sqltypes.AutoString(length=400), nullable=False
        ),
        sa.Column(
            "tipo_observacion",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
        sa.Column("fecha", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["docente_id"],
            ["docente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["periodo_id"],
            ["periodo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cafeteria",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("estudiante_id", sa.Integer(), nullable=False),
        sa.Column("periodo_id", sa.Integer(), nullable=False),
        sa.Column("estado_cafeteria", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
        ),
        sa.ForeignKeyConstraint(
            ["periodo_id"],
            ["periodo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "detalleescuelaformacion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("complementario_id", sa.Integer(), nullable=False),
        sa.Column("estudiante_id", sa.Integer(), nullable=False),
        sa.Column("fecha_registro", sa.DateTime(), nullable=False),
        sa.Column("mes", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("estado_escuela", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["complementario_id"],
            ["complementario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "detalleprueba",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("estudiante_id", sa.Integer(), nullable=False),
        sa.Column("complementario_id", sa.Integer(), nullable=False),
        sa.Column(
            "tipo_prueba", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("fecha_registro", sa.DateTime(), nullable=False),
        sa.Column("estado", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["complementario_id"],
            ["complementario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "matricula",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("para_matricula_id", sa.Integer(), nullable=False),
        sa.Column("estudiante_id", sa.Integer(), nullable=False),
        sa.Column("periodo_id", sa.Integer(), nullable=False),
        sa.Column("valor_total", sa.Integer(), nullable=False),
        sa.Column("fecha_registro", sa.DateTime(), nullable=False),
        sa.Column("estado_matricula", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
        ),
        sa.ForeignKeyConstraint(
            ["para_matricula_id"],
            ["parametrizarmatricula.id"],
        ),
        sa.ForeignKeyConstraint(
            ["periodo_id"],
            ["periodo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "observador",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("estudiante_id", sa.Integer(), nullable=False),
        sa.Column(
            "tipo_incidencia",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
        sa.Column(
            "descripcion", sqlmodel.sql.sqltypes.AutoString(length=400), nullable=False
        ),
        sa.Column("fecha", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pension",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("para_pension_id", sa.Integer(), nullable=False),
        sa.Column("estudiante_id", sa.Integer(), nullable=False),
        sa.Column("grado_id", sa.Integer(), nullable=False),
        sa.Column("valor_total", sa.Integer(), nullable=False),
        sa.Column("fecha_registro", sa.DateTime(), nullable=False),
        sa.Column("estado_pension", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
        ),
        sa.ForeignKeyConstraint(
            ["grado_id"],
            ["grado.id"],
        ),
        sa.ForeignKeyConstraint(
            ["para_pension_id"],
            ["parametrizarpension.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prestamo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("inventario_id", sa.Integer(), nullable=False),
        sa.Column("estudiante_id", sa.Integer(), nullable=False),
        sa.Column("fecha_salida", sa.DateTime(), nullable=False),
        sa.Column("fecha_devolucion", sa.DateTime(), nullable=False),
        sa.Column("estado_prestamo", sa.Boolean(), nullable=False),
        sa.Column(
            "observacion", sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inventario_id"],
            ["inventario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pupitre",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("estudiante_id", sa.Integer(), nullable=False),
        sa.Column("estado_pupitre", sa.Boolean(), nullable=False),
        sa.Column(
            "observacion", sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "detallematricula",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("matricula_id", sa.Integer(), nullable=False),
        sa.Column("complementario_id", sa.Integer(), nullable=False),
        sa.Column("cuota", sa.Integer(), nullable=False),
        sa.Column("descuento", sa.Integer(), nullable=False),
        sa.Column("valor_completo", sa.Integer(), nullable=False),
        sa.Column("valor_pendiente", sa.Integer(), nullable=False),
        sa.Column("fecha_abono", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["complementario_id"],
            ["complementario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["matricula_id"],
            ["matricula.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "detallepazysalvo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("estudiante_id", sa.Integer(), nullable=False),
        sa.Column("prestamo_id", sa.Integer(), nullable=False),
        sa.Column("cafeteria_id", sa.Integer(), nullable=False),
        sa.Column("matricula_id", sa.Integer(), nullable=False),
        sa.Column("pension_id", sa.Integer(), nullable=False),
        sa.Column("pupitre_id", sa.Integer(), nullable=False),
        sa.Column("complemento_id", sa.Integer(), nullable=False),
        sa.Column("estado_escuela", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cafeteria_id"],
            ["cafeteria.id"],
        ),
        sa.ForeignKeyConstraint(
            ["complemento_id"],
            ["complementario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
        ),
        sa.ForeignKeyConstraint(
            ["matricula_id"],
            ["matricula.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pension_id"],
            ["pension.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prestamo_id"],
            ["prestamo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pupitre_id"],
            ["pupitre.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "detallepension",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("pension_id", sa.Integer(), nullable=False),
        sa.Column("detalle_matricula_id", sa.Integer(), nullable=False),
        sa.Column("mes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["detalle_matricula_id"],
            ["detallematricula.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pension_id"],
            ["pension.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pazysalvo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("detalle_pazysalvo_id", sa.Integer(), nullable=False),
        sa.Column("periodo_id", sa.Integer(), nullable=False),
        sa.Column(
            "estado_final", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("fecha", sa.DateTime(), nullable=False),
        sa.Column(
            "observacion", sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["detalle_pazysalvo_id"],
            ["detallepazysalvo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["periodo_id"],
            ["periodo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pazysalvo")
    op.drop_table("detallepension")
    op.drop_table("detallepazysalvo")
    op.drop_table("detallematricula")
    op.drop_table("pupitre")
    op.drop_table("prestamo")
    op.drop_table("pension")
    op.drop_table("observador")
    op.drop_table("matricula")
    op.drop_table("detalleprueba")
    op.drop_table("detalleescuelaformacion")
    op.drop_table("cafeteria")
    op.drop_table("rectoriaobservaciones")
    op.drop_table("rectoriaestado")
    op.drop_table("parametrizarpension")
    op.drop_table("parametrizarmatricula")
    op.drop_table("inventario")
    op.drop_table("estudiante")
    op.drop_table("detalleactividades")
    op.drop_table("auditoria")
    op.drop_table("usuario")
    op.drop_index(op.f("ix_tipoinventario_nombre"), table_name="tipoinventario")
    op.drop_table("tipoinventario")
    op.drop_table("periodo")
    op.drop_table("importacionautomatica")
    op.drop_table("grado")
    op.drop_table("docente")
    op.drop_table("complementario")
    op.drop_table("acudiente")
    op.drop_table("actividad")
    # ### end Alembic commands ###
