"""feat: add observador table for module 9

Revision ID: 1efa10f067d4
Revises: b4b043cd3c78
Create Date: 2026-05-27 10:15:07.988882

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '1efa10f067d4'
down_revision: Union[str, Sequence[str], None] = 'b4b043cd3c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
