"""add motivo_baja to detalleescuelaformacion

Revision ID: 60a8206120d4
Revises: f98bcbcfbcbd
Create Date: 2026-05-23 14:25:01.555880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '60a8206120d4'
down_revision: Union[str, Sequence[str], None] = 'f98bcbcfbcbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalleescuelaformacion', sa.Column('motivo_baja', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detalleescuelaformacion', 'motivo_baja')
    # ### end Alembic commands ###
