"""add_missing_fields_to_observador

Revision ID: 9d7f73fd0fd2
Revises: 1efa10f067d4
Create Date: 2026-05-27 11:25:06.386088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7f73fd0fd2'
down_revision: Union[str, Sequence[str], None] = '1efa10f067d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observador', sa.Column('docente_id', sa.Integer(), nullable=False))
    op.add_column('observador', sa.Column('esta_abierta', sa.Boolean(), nullable=False))
    op.add_column('observador', sa.Column('fecha_cierre', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observador', 'fecha_cierre')
    op.drop_column('observador', 'esta_abierta')
    op.drop_column('observador', 'docente_id')
    # ### end Alembic commands ###
